# Site settings
title: Erdenkrieger.in
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/creative-theme-jekyll-new/" # the subpath of your site, e.g. /blog/
url: "test.erdenkrieger.in" # the base hostname & protocol for your site
author: Copyright &copy; 2019 - Start Bootstrap
lang: de_DE

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
