backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/img" # Media files will be stored in the repo under images/uploads

# These lines should *not* be indented
media_folder: "assets/img" # Media files will be stored in the repo under static/images/uploads

